galaxy_info:
  author: wiqt8r
  description: Role for installing and configuring Vector
  license: MIT
  min_ansible_version: "2.12"

  role_name: vector
  namespace: wiqt8r

  platforms:
    - name: EL
      versions:
        - "8"
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
