some_fact: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61633139323565623762366531363538666565613566396139373162356664656661353931333164
          3362616330633233393636326138363937396532616430350a303061323634623765343664623937
          61366538333530363432393031633361616138343538666236653632303037656538626438623434
          3230613334633639640a306138366563383162383064393633653265663831393665666634393037
          6637
