---
vector_version: "0.51.1"
vector_install_dir: "/opt/vector"
vector_config_dir: "/etc/vector"

# ссылка на вектор:
vector_download_url: "https://packages.timber.io/vector/0.51.1/vector-x86_64-unknown-linux-gnu.tar.gz"

