---
- name: Install Clickhouse
  hosts: clickhouse
  tags: [clickhouse]
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: Download clickhouse client/server (noarch) to control node
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
        dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
        mode: "0644"
      loop: "{{ clickhouse_packages | difference(['clickhouse-common-static']) }}"
      delegate_to: localhost
      when: not ansible_check_mode

    - name: Download clickhouse-common-static (x86_64) to control node
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
        dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
        mode: "0644"
      delegate_to: localhost
      when: not ansible_check_mode

    - name: Copy Clickhouse packages to target host
      ansible.builtin.copy:
        src: "./{{ item }}-{{ clickhouse_version }}.rpm"
        dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
        mode: "0644"
      loop: "{{ clickhouse_packages }}"
      when: not ansible_check_mode

    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:  # noqa fqcn[action-core]
        name:
          - "clickhouse-common-static-{{ clickhouse_version }}.rpm"
          - "clickhouse-client-{{ clickhouse_version }}.rpm"
          - "clickhouse-server-{{ clickhouse_version }}.rpm"
        disable_gpg_check: true
      notify: Start clickhouse service
      when: not ansible_check_mode

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
      when: not ansible_check_mode

- name: Install Vector
  hosts: vector
  tags: [vector]
  handlers:
    - name: Restart vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
      when: not ansible_check_mode and ansible_virtualization_type != 'docker'

  tasks:
    - name: Copy vector archive from repository
      ansible.builtin.copy:
        src: "files/vector-{{ vector_version }}.tar.gz"
        dest: "/tmp/vector-{{ vector_version }}.tar.gz"
        mode: "0644"

    - name: Create vector installation directory
      ansible.builtin.file:
        path: "{{ vector_install_dir }}"
        state: directory
        mode: "0755"

    - name: Unpack vector archive
      ansible.builtin.unarchive:
        src: "/tmp/vector-{{ vector_version }}.tar.gz"
        dest: "{{ vector_install_dir }}"
        remote_src: true
        creates: "{{ vector_install_dir }}/bin/vector"
      when: not ansible_check_mode

    - name: Create symlink for vector binary
      ansible.builtin.file:
        src: "{{ vector_install_dir }}/bin/vector"
        dest: "/usr/local/bin/vector"
        state: link
      when: not ansible_check_mode

    - name: Create vector config directory
      ansible.builtin.file:
        path: "{{ vector_config_dir }}"
        state: directory
        mode: "0755"

    - name: Deploy vector config
      ansible.builtin.template:
        src: "vector.yml.j2"
        dest: "{{ vector_config_dir }}/vector.yml"
        mode: "0644"
      notify: Restart vector service

    - name: Install vector systemd unit
      ansible.builtin.template:
        src: "vector.service.j2"
        dest: "/etc/systemd/system/vector.service"
        mode: "0644"
      notify: Restart vector service

    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
      when: not ansible_check_mode and ansible_virtualization_type != 'docker'

    - name: Ensure vector service is enabled and running
      become: true
      ansible.builtin.service:
        name: vector
        state: started
        enabled: true
      when: not ansible_check_mode and ansible_virtualization_type != 'docker'

- name: Install Lighthouse
  hosts: lighthouse
  tags: [lighthouse]
  handlers:
    - name: Restart nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: not ansible_check_mode

  tasks:
    - name: Install nginx on RedHat family
      become: true
      ansible.builtin.yum:  # noqa fqcn[action-core]
        name:
          - nginx
          - git
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install nginx on Debian family
      become: true
      ansible.builtin.apt:
        name:
          - nginx
          - git
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Create lighthouse docroot directory
      become: true
      ansible.builtin.file:
        path: "{{ lighthouse_docroot }}"
        state: directory
        mode: "0755"

    - name: Clone lighthouse repository
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_repo_url }}"
        dest: "{{ lighthouse_docroot }}"
        version: master
        force: true
      when: not ansible_check_mode

    - name: Deploy nginx config for lighthouse
      become: true
      ansible.builtin.template:
        src: "lighthouse.conf.j2"
        dest: "{{ lighthouse_nginx_conf }}"
        mode: "0644"
      notify: Restart nginx

    - name: Ensure nginx is enabled and running
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      when: not ansible_check_mode
